# Site settings
title: SCENEE Tech Blog
email: shin2smile@gmail.com
description: | #> # this means to ignore newlines until "baseurl:"
  Welcom! I'm SCENEE[/siÀêni/]. Software Development Engineer.
  My Goal is to create incredible products in short life.
  I like Unix philosophy. so I like Unix, Linux and C.
  Also I like iOS, ObjC and Swift.
  Recently I have been intersted in wireless technologies
  and functional programming using Erlang.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: SCENEE
github_username:  SCENEE

# Build settings
markdown: kramdown
kramdown:
  input: GFM
